### PR TITLE
Initial schema proposal 

### PR DESCRIPTION
**Pull request by DanInci**

### CODE REVIEW

**Comment by almutlue** [comment]
There are still some main discrepancies between the example `benchmar-001.yaml` and `omni-schema`.
- __Prameter__: What about adding a `values` slot to `Parameter` and changing `parameters` to `ParameterCollection`?
- __Inputs__: We do not use file paths for inputs in the current yaml file format, but indirectly infer them from the specified stage and types outputs. So we either need to separate `IOFile` for outputs and inputs or we change the yaml. 
A possibility is also to extend the yaml towards a more explicit, but also verbose format for now?

**Comment by DanInci** [comment]
Fixed discrepancies mentioned by @almutlue in order to have a functioning initial [schema](https://github.com/omnibenchmark/omni-schema/blob/feat/dincicau_basics/src/omni_schema/schema/omni_schema.yaml). 

- **Parameter**: I agree, I added a `values` slot, but modeled the content as a vector of strings. Raw parameter strings can be processed initially to get refined parameters input: e.g. `"-a 0 -b 0.1"` -> `["-a 0", "-b 0.1"]`
- **Inputs**: I made the `IOFile` extend `IdentifiableEntity` and so each has a unique id. As an input, we can then reference by id a specific `IOFile`. The `IOFile` itself represents the concept of an output from a previous step, not necessary the materalised output file. By linking the input to an output, we can then use the `path` (path format) to figure out the exact materialsed input file we need.

**Comment by DanInci** [comment]
Proposed model looks like this, and it validates an example [benchmark yaml](https://github.com/omnibenchmark/omni-schema/blob/feat/dincicau_basics/src/data/examples/Benchmark-001.yaml).

[Parameter|values:string *],[Benchmark|platform:string;id(i):uriorcurie;name(i):string;description(i):string %3F]++- orchestrator 1..1>[Orchestrator|name:string;url:string],[Module]<exclude 0..*- [Module],[Step|initial:boolean %3F;terminal:boolean %3F;id(i):uriorcurie;name(i):string;description(i):string %3F]++- members 1..*>[Module],[IdentifiableEntity|id:uriorcurie;name:string;description:string %3F]^-[Module],[IOFile|path:string %3F;id(i):uriorcurie;name(i):string;description(i):string %3F]<outputs 0..*-++[Step],[InputCollection]<inputs 0..*-++[Step],[Step]<after 0..*- [Step],[Benchmark]++- steps 1..*>[Step],[IdentifiableEntity]^-[Step],[IOFile]<entries 0..*- [InputCollection],[Step]++- inputs 0..*>[InputCollection],[IdentifiableEntity]^-[Step],[IdentifiableEntity]^-[Module],[IdentifiableEntity]^-[IOFile],[IdentifiableEntity]^-[Benchmark],[InputCollection]- entries 0..*>[IOFile],[Step]++- outputs 0..*>[IOFile],[Benchmark]">

**Comment by DanInci** [comment]
Now, LinkML and this model will help us have a single source of truth in terms of domain model. The yaml schema can be exported as SQL, JSON, RDF and python classes.

However, the proposed [`starts_to_be_explicit.yaml`](https://github.com/omnibenchmark/omni-schema/blob/feat/dincicau_basics/src/reference/starts_to_be_explicit.yaml) is still a bit different than what the current schema can validate, [`Benchmark-001.yaml`](https://github.com/omnibenchmark/omni-schema/blob/feat/dincicau_basics/src/data/examples/Benchmark-001.yaml). How different? Well, let's compare:

```diff
--- starts_to_be_explicit.yaml
+++ Benchmark-001.yaml
@@ -1,4 +1,5 @@
 ---
+id: Benchmark-001
 name: starts_to_be_explicit
 description: simple benchmark, somewhat explicit, simple params
 platform: https://gitlab.renkulab.io/
@@ -6,72 +7,106 @@
   name: orchestrator
   url: https://gitlab.renkulab.io/omnibenchmark/test/orchestrator
 steps:
-  data:
+  - id: Step1
+    name: data
     initial: true
     members:
-      - name: D1
+      - id: D1
+        name: D1
         repo: omnibenchmark/test/D1
-      - name: D2
+      - id: D2
+        name: D2
         repo: omnibenchmark/test/D2
     outputs:
-      - counts: "{stage}/{module}/{params}/{name}.txt.gz"
-      - meta: "{stage}/{module}/{params}/{name}.meta.json"
-      - data_specific_params: "{stage}/{module}/{params}/{name}_params.txt"
-  process:
+      - id: Step1.counts
+        name: counts
+        path: "{stage}/{module}/{params}/{name}.txt.gz"
+      - id: Step1.meta
+        name: meta
+        path: "{stage}/{module}/{params}/{name}.meta.json"
+      - id: Step1.data_specific_params
+        name: data_specific_params
+        path: "{stage}/{module}/{params}/{name}_params.txt"
+
+  - id: Step2
+    name: process
     after:
       - data
     members:
-      - name: P1
+      - id: P1
+        name: P1
         repo: omnibenchmark/test/P1
         parameters:
-          - -a 0, -b 0.1
-          - -a 1 -b 0.1
-      - name: P2
+          - values: ["-a 0", "-b 0.1"]
+          - values: ["-a 1", "-b 0.1"]
+      - id: P2
+        name: P2
         repo: omnibenchmark/test/P2
         parameters:
-          - -a 0 -c 0
-          - -a 1 -c 0.1
+          - values: ["-a 0", "-c 0"]
+          - values: ["-a 1", "-c 0.1"]
     inputs:
-      - counts: data
-        meta: data
+      - entries: [
+          Step1.counts,
+          Step1.meta
+        ]
     outputs:
-      - filtered: "{input_dirname}/{stage}/{module}/{params}/{name}.txt.gz"
-  methods:
+      - id: Step2.filtered
+        name: filtered
+        path: "{input_dirname}/{stage}/{module}/{params}/{name}.txt.gz"
+
+  - id: Step3
+    name: methods
     after:
       - process
     members:
-      - name: M1
+      - id: M1
+        name: M1
         repo: benchmark/test/M1
-        exclude: D2
-      - name: M2
+        exclude: [ D2 ]
+      - id: M2
+        name: M2
         repo: omnibenchmark/test/M2
         parameters:
-          - -d1 -e1
-          - -d1 -e 2
+          - values: ["-d1", "-e 1"]
+          - values: ["-d1", "-e 2"]
         exclude:
           - D1
           - D2
     inputs:
-      - counts: data
-        meta: data
-        data_specific_params: data
-      - filtered: process
-        meta: data
-        data_specific_params: data
+      - entries: [
+          Step1.counts,
+          Step1.meta,
+          Step1.data_specific_params
+        ]
+      - entries: [
+          Step2.filtered,
+          Step1.meta,
+          Step1.data_specific_params
+        ]
     outputs:
-      - mapping: "{input_dirname}/{stage}/{module}/{params}/{name}.model.out.gz"
-  metrics:
+      - id: Step3.mapping
+        name: mapping
+        path: "{input_dirname}/{stage}/{module}/{params}/{name}.model.out.gz"
+
+  - id: Step4
+    name: metrics
     after:
       - methods
     terminal: true
     members:
-      - name: m1
+      - id: m1
+        name: m1
         repo: omnibenchmark/test/m1
-      - name: m2
+      - id: m2
+        name: m2
         repo: omnibenchmark/test/m2
-      - name: m3
+      - id: m3
+        name: m3
         repo: omnibenchmark/test/m3
     inputs:
-      - mapping: method
-        meta: data
-        data_specific_params: data
+      - entries: [
+          Step3.mapping,
+          Step1.meta,
+          Step1.data_specific_params
+        ]
```

Now there are multiple possibilities to mitigate this differences that I see fit:
1. Learn from the experience of designing the LinkML schema and update the original `starts_to_be_explicit.yaml` schema.
2. Update the LinkML `omni_schema.yaml` schema.
3. Map the benchmark definition data from the original format to the LinkML format on the fly. This will work since it involves only introducing some unique ids and straightforward transformations.

What are your suggestions about it? Does the data model make sense to you?

**Comment by almutlue** [comment]
Great! Looks very good to me. Shall we merge?

**Pull request merged**
